#端口号
server:
  port: 8761
spring:
  application:
    name: Eureka-Server
#eureka配置
eureka:
  instance:
    hostname: peer1  #主机名
  client:
    register-with-eureka: true   #表示是否将服务注册到Eureka服务端(默认是true)当搭建eureka集群的时候将参数改为true；
    fetch-registry: true  #表示是否从Eureka服务端获取服务信息(默认是true)当搭建eureka集群的时候将参数改为true；
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/