#端口号
server:
  port: 8762
spring:
  application:
    name: Eureka-Server
#eureka配置
eureka:
  instance:
    hostname: peer2  #主机名
  client:
    register-with-eureka: true   #表示是否将服务注册到Eureka服务端,由于自身就是Eureka服务端，所以设置为false；
    fetch-registry: true  #表示是否从Eureka服务端获取服务信息，因为这里只搭建了一个Eureka服务端，并不需要从别的Eureka服务端同步服务信息，所以这里设置为false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
#配置文件命名符合application-{profile}.yml这种的规范，那么我们在这里面可以省略application-的前缀和.yml的后缀，只需写profile即可