#端口号
server:
  port: 8081
spring:
  application:
    name: provider
#eureka配置
eureka:
  instance:
    statusPageUrlPath: /info
  client:
    register-with-eureka: true   #表示是否将服务注册到Eureka服务端,由于自身就是Eureka服务端，所以设置为false；
    fetch-registry: true  #表示是否从Eureka服务端获取服务信息，因为这里只搭建了一个Eureka服务端，并不需要从别的Eureka服务端同步服务信息，所以这里设置为false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
